const students = [
  { name: "سما شلبي", section: 11 },
  { name: "محمد أبو زهره", section: 9 },
  { name: "طارق صايمه", section: 10 },
  { name: "عبد الله تلأحمه", section: 10 },
  { name: "ابراهيم عبدالله", section: 9 },
  { name: "بتول أبوسمن", section: 10 },
  { name: "عبد الله خضير", section: 9 },
  { name: "أحمد نمر", section: 9 },
  { name: "يوسف خدرج", section: 9 },
  { name: "الاء عوده", section: 11 },
  { name: "حلى خليفه", section: 9 },
  { name: "أسامه أبو ريش", section: 10 },
  { name: "أسامه شولي", section: 10 },
  { name: "أحمد منصور", section: 10 },
  { name: "معاويه اسماعيل", section: 10 },
  { name: "عامر أبو زيتون", section: 9 },
  { name: "عبد الرحمن جندي", section: 10 },
  { name: "ابراهيم خضير", section: 9 },
  { name: "محمد صوالحه", section: 10 },
  { name: "الاء قاقا", section: 11 },
  { name: "عباده عصيده", section: 11 },
  { name: "عمر استيتيه", section: 9 },
  { name: "أرين شماسنه", section: 11 },
  { name: "سيف العيش", section: 9 },
  { name: "رهف حناين", section: 9 },
  { name: "عماد المصري", section: 10 },
  { name: "عزالدين مقبل", section: 11 },
  { name: "محمد قزيح", section: 11 },
  { name: "نسيم سلعوس", section: 9 },
  { name: "أحمد نمروطي", section: 11 },
  { name: "محمد علاونه", section: 9 },
  { name: "أحمد حماده", section: 11 },
  { name: "طه أبو السعود", section: 9 },
  { name: "ريما كوسا", section: 9 },
  { name: "ايمان عثمان", section: 9 },
  { name: "نورهان كوسا", section: 11 },
  { name: "اسماعيل دويكات", section: 10 },
  { name: "حمزة سايح", section: 10 },
  { name: "رغد محمود", section: 9 },
  { name: "داليا خليلي", section: 9 },
  { name: "ساره شاهين", section: 9 },
  { name: "أحمد ظاهر", section: 10 },
  { name: "عبد الرحمن عاصي", section: 10 },
  { name: "نور الهدى دراغمه", section: 10 },
  { name: "ايمن صوالحه", section: 11 },
  { name: "سميره نجار", section: 9 },
  { name: "رناد عويضات", section: 10 },
  { name: "ماسه عطا الله", section: 9 },
  { name: "إيناس ياسين", section: 9 },
  { name: "ماهر طوباسي", section: 10 },
  { name: "عمر هواش", section: 9 },
  { name: "رؤى جدعه", section: 9 },
  { name: "دانا عبد الحق", section: 11 },
  { name: "عبد الرحمن داود", section: 9 },
  { name: "عز الدين شخشير", section: 9 },
  { name: "فرح صالح", section: 9 },
  { name: "محمود عمد", section: 9 },
  { name: "أحمد سليمان", section: 9 },
  { name: "هادي ديريه", section: 10 },
  { name: "بيان عبد الحق", section: 10 },
  { name: "نور كلبونه", section: 11 },
  { name: "عبد الله عثمان", section: 9 },
  { name: "عماد السلخي", section: 9 },
  { name: "بروج عديلي", section: 11 },
  { name: "محمد عواوده", section: 10 },
  { name: "يمان أبوالعدس", section: 9 },
  { name: "عمر حمدان", section: 10 },
  { name: "صبري أبو عقل", section: 10 },
  { name: "غسان مقبول", section: 11 },
  { name: "وفاء حوراني", section: 11 },
  { name: "رغد صوان", section: 11 },
  { name: "باسل ترك", section: 11 },
  { name: "الاء عفوري", section: 11 },
  { name: "لجين شمسه", section: 10 },
  { name: "رهف أبوسيفين", section: 10 },
  { name: "هادي سوالمه", section: 11 },
  { name: "ليال عواد", section: 10 },
  { name: "شيماء سليم", section: 10 },
  { name: "ابراهيم بليه", section: 11 },
  { name: "ملاك موسى", section: 9 },
];
